title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  A simple and clean Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iphoneeeee.github.io" # the base hostname & protocol for your site
remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme

# Customization
theme: modernist
show_downloads: true

# Build settings
markdown: kramdown
